# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from securerag.proto import secure_retrieval_pb2 as securerag_dot_proto_dot_secure__retrieval__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in securerag/proto/secure_retrieval_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecureRetrievalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chunk = channel.unary_unary(
                '/securerag.SecureRetrieval/Chunk',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.ChunkRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.Sanitize = channel.unary_unary(
                '/securerag.SecureRetrieval/Sanitize',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.SanitizeRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.SanitizeResponse.FromString,
                _registered_method=True)
        self.BuildIndex = channel.unary_unary(
                '/securerag.SecureRetrieval/BuildIndex',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.BuildIndexRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.BuildIndexResponse.FromString,
                _registered_method=True)
        self.GenerateDecoys = channel.unary_unary(
                '/securerag.SecureRetrieval/GenerateDecoys',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.GenerateDecoysRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.GenerateDecoysResponse.FromString,
                _registered_method=True)
        self.BatchRetrieve = channel.unary_unary(
                '/securerag.SecureRetrieval/BatchRetrieve',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.BatchRetrieveRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.BatchRetrieveResponse.FromString,
                _registered_method=True)
        self.EmbedWithNoise = channel.unary_unary(
                '/securerag.SecureRetrieval/EmbedWithNoise',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.EmbedWithNoiseRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.EmbedWithNoiseResponse.FromString,
                _registered_method=True)
        self.RetrieveByEmbedding = channel.unary_unary(
                '/securerag.SecureRetrieval/RetrieveByEmbedding',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.RetrieveByEmbeddingRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.RetrieveByEmbeddingResponse.FromString,
                _registered_method=True)
        self.EncryptedSearch = channel.unary_unary(
                '/securerag.SecureRetrieval/EncryptedSearch',
                request_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.EncryptedSearchRequest.SerializeToString,
                response_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.EncryptedSearchResponse.FromString,
                _registered_method=True)


class SecureRetrievalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sanitize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDecoys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRetrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedWithNoise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveByEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptedSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecureRetrievalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chunk': grpc.unary_unary_rpc_method_handler(
                    servicer.Chunk,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.ChunkRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.ChunkResponse.SerializeToString,
            ),
            'Sanitize': grpc.unary_unary_rpc_method_handler(
                    servicer.Sanitize,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.SanitizeRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.SanitizeResponse.SerializeToString,
            ),
            'BuildIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildIndex,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.BuildIndexRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.BuildIndexResponse.SerializeToString,
            ),
            'GenerateDecoys': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDecoys,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.GenerateDecoysRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.GenerateDecoysResponse.SerializeToString,
            ),
            'BatchRetrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRetrieve,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.BatchRetrieveRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.BatchRetrieveResponse.SerializeToString,
            ),
            'EmbedWithNoise': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedWithNoise,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.EmbedWithNoiseRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.EmbedWithNoiseResponse.SerializeToString,
            ),
            'RetrieveByEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveByEmbedding,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.RetrieveByEmbeddingRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.RetrieveByEmbeddingResponse.SerializeToString,
            ),
            'EncryptedSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptedSearch,
                    request_deserializer=securerag_dot_proto_dot_secure__retrieval__pb2.EncryptedSearchRequest.FromString,
                    response_serializer=securerag_dot_proto_dot_secure__retrieval__pb2.EncryptedSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'securerag.SecureRetrieval', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('securerag.SecureRetrieval', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecureRetrieval(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/Chunk',
            securerag_dot_proto_dot_secure__retrieval__pb2.ChunkRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sanitize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/Sanitize',
            securerag_dot_proto_dot_secure__retrieval__pb2.SanitizeRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.SanitizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/BuildIndex',
            securerag_dot_proto_dot_secure__retrieval__pb2.BuildIndexRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.BuildIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDecoys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/GenerateDecoys',
            securerag_dot_proto_dot_secure__retrieval__pb2.GenerateDecoysRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.GenerateDecoysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchRetrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/BatchRetrieve',
            securerag_dot_proto_dot_secure__retrieval__pb2.BatchRetrieveRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.BatchRetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedWithNoise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/EmbedWithNoise',
            securerag_dot_proto_dot_secure__retrieval__pb2.EmbedWithNoiseRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.EmbedWithNoiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveByEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/RetrieveByEmbedding',
            securerag_dot_proto_dot_secure__retrieval__pb2.RetrieveByEmbeddingRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.RetrieveByEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncryptedSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securerag.SecureRetrieval/EncryptedSearch',
            securerag_dot_proto_dot_secure__retrieval__pb2.EncryptedSearchRequest.SerializeToString,
            securerag_dot_proto_dot_secure__retrieval__pb2.EncryptedSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
